packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - cypress
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

patchedDependencies:
  d3-graph-react@1.3.1: patches/d3-graph-react@1.3.1.patch
