export interface HealthResponse {
  status: 'ok';
  timestamp: string;
}

export interface TechnicalQueryRequest {
  query: string;
}

/** Indexed article metadata; unknown fields are explicitly null. */
export interface KnowledgeGraphSource {
  articleTitle: string | null;
  blogName: string | null;
  publishedAt: string | null;
}

/** A concept and its grounded article URL, or null when it has no source. */
export interface KnowledgeGraphNode {
  id: string;
  label: string;
  type: 'concept';
  sourceUrl: string | null;
  /** Provenance from indexed chunks, never generated by the language model. */
  source?: KnowledgeGraphSource | null;
}

export interface KnowledgeGraphEdge {
  source: string;
  target: string;
  relationship: string;
}

/**
 * `centralNodeId` is the node holding the main idea (post) of the graph. Every
 * other node is at most 3 levels away from it. It is `null` only when the graph
 * has no nodes.
 */
export interface KnowledgeGraph {
  nodes: KnowledgeGraphNode[];
  edges: KnowledgeGraphEdge[];
  centralNodeId: string | null;
}

/**
 * Final response for `POST /technical-queries`: a natural-language summary plus
 * an interactive knowledge graph whose nodes may link back to their source URL.
 */
export interface TechnicalQueryResponse {
  summary: string;
  graph: KnowledgeGraph;
}
